[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
lending_market = "XnZM1abpYCvCQCDfYATfHgnkF2xQF4bph5ThJYK26Wh"
liquidation = "5mpktkWnqXD89hDDVGczSHytVuWXyTAinKNW8KjjVGJB"
reserve = "E1GYsEPRoPk7oCXhnCfBmEDpj6L6YYaeiz5ZWk8DapWW"
underwriting = "AAPzJhMAm8Lqm1qMNQdgmqtA4cpUktWnuzAg8QQ7V8qs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
